// src/products.js
export const productsData = [
  {
    id: 1,
    name: "Туалетное мыло Dove",
    category: "Красота и уход",
    price: 120,
    description: "Количество: 1 шт.\nБольшой выбор ароматов",
    images: ["/images/DOVE.jpg"],
    status: "в наличии",
  },
  {
    id: 2,
    name: "Роза-букет",
    category: "Искусственные цветы",
    price: 150,
    description: "Количество голов: 13 шт.\nРазмер: 38 см",
    images: ["/images/roza.JPG"],
    status: "в наличии",
  },
  {
    id: 3,
    name: "Туалетное мыло Nova",
    category: "Красота и уход",
    price: 420,
    description: "Упаковка-6шт.\nМикс ароматов",
    images: ["/images/NOVA.jpg"],
    status: "в наличии",
  },
  {
    id: 4,
    name: "Шампунь Pantene",
    category: "Красота и уход",
    price: 220,
    description: "Шампунь Pantene (400 мл), разных видов и назначений.",
    images: ["/images/pantene.jpg"],
    status: "в наличии",
  },
  {
    id: 5,
    name: "Шампунь Head & Shoulders",
    category: "Красота и уход",
    price: 220,
    description:
      "Шампунь Head & Shoulders (400 мл), разных видов и назначений.",
    images: ["/images/shoulders.jpg"],
    status: "в наличии",
  },
  {
    id: 6,
    name: "Мерцающая соль",
    category: "Красота и уход",
    price: 100,
    description: "Мерцающая соль для ванны\nОбъем 500гр",
    images: ["/images/sol.jpg"],
    status: "в наличии",
  },
  {
    id: 7,
    name: "Туалетное мыло Winex",
    category: "Красота и уход",
    price: 200,
    description: "Упаковка-4шт\nМикс ароматов",
    images: ["/images/winex.jpg"],
    status: "в наличии",
  },
  {
    id: 8,
    name: "Тинт для губ",
    category: "Красота и уход",
    price: 360,
    description: "Тинт для губ\nНабор из 6 шт",
    images: ["/images/tint.jpg", "/images/tint1.jpg"],
    status: "в наличии",
  },
  {
    id: 9,
    name: "Блеск для губ",
    category: "Красота и уход",
    price: 350,
    description: "Набор тинт блеск для губ Rhode 4 шт",
    images: ["/images/blesk.jpg"],
    status: "в наличии",
  },
  {
    id: 10,
    name: "Освежитель воздуха",
    category: "Красота и уход",
    price: 150,
    description: "Освежитель воздуха Air freshener",
    images: ["/images/air.jpg"],
    status: "в наличии",
  },
  {
    id: 11,
    name: "Плед",
    category: "Текстиль",
    price: 360,
    description: "Покрывало-плед из микрофибры.\nРазмер: 200х220 см",
    images: [
      "/images/pledbambuk1.jpg",
      "/images/pledbambuk2.jpg",
      "/images/pledbambuk3.jpg",
      "/images/pledbambuk4.jpg",
      "/images/pledbambuk5.jpg",
      "/images/pledbambuk6.jpg",
      "/images/pledbambuk7.jpg",
      "/images/pledbambuk8.jpg",
      "/images/pledbambuk9.jpg",
    ],
    status: "Под заказ",
  },
];
